### ISSUE TITLE
HELM

### ISSUE THREAD

**Issue by KilJaeeun** [KilJaeeun/TIL#13]

**Comment by KilJaeeun** [comment]
# built-in object
- ``{{}}` 이용
- values  에서나 다른 곳에서 가져옴

**Comment by KilJaeeun** [comment]
# builtin function
https://helm.sh/docs/chart_template_guide/functions_and_pipelines/
- `quote .`:

**Comment by KilJaeeun** [comment]
# Flow Control . if/else



### sudo code

```
{{ if PIPELINE }}
# do
{{ els if OTHER PIPELINE}}
# do else
{{ else }}
# default
{{ end }}
```





```yaml
  projectCode: aazzxxyy
   infra:
     zone: a,b,c
     region: us-e


 {{ if eq .Values.infra.region "us-e" }}ha: true{{ end }}



```



```sh
 helm install --dry-run --debug controlif ./mychart


 helm install controlif ./mychart 


 helm get manifest controlif

 helm uninstall controlif 


```

    ```sh
 //Error
{{ if eq .Values.infra.region "us-e" }}
     ha: true
{{ end }}


{{ if eq .Values.infra.region "us-e" }}
ha: true
{{ end }}

{{- if eq .Values.infra.region "us-e" }}
ha: true
{{- end }}

//Should not be done. Error

{{- if eq .Values.infra.region "us-e" -}}
 ha: true
{{- end -}}
    ```






​

**Comment by KilJaeeun** [comment]
https://tech.ktcloud.com/51
helm 은 공식 홈페이지에서 정의가 나온 것처럼 k8s 패키지 관리를 도와준다. 흔히 패키지 관리를 도와주는 node js 의 npm 과 python 의 pip 와 같은 역할이다. 
helm 은 3가지  주요 개념이 있다.

1. chart 
차트 
helm 패키지로 k8s 클러스터에서 애플리케이션이 기동되기 위해 필요한 모든 리소스 들이 포함된다. 
아래 이미지와 같이 mariadb를 기동하기 위해 필요한 리소스인 deploy, secret, service 가 생성되는 것을 볼 수 있다. 
2. repository 
저장소
차트 저장소로 차트를 모아두고 공유하는 장소입니다.

3. release 릴리즈
k8s 클러스터에서 구동되는 차트 인스턴스이다. 일반적으로 동일한 chart 를 여러번 설치할 수 있고, 이는  새로운 release 로 관리된다. release 될때 패키지된 차트와 config 가 결합돼 정상 실행되게 된다.


아래와 같은 순서로 연계되는데
k8s cluster 내부에 helm 차트를 원하는 repository 에서 검색 후 설치 => 각 설치에 따른 새로운 release 생성

**Comment by KilJaeeun** [comment]
https://www.youtube.com/watch?v=Zzwq9FmZdsU&t=2s

**Comment by KilJaeeun** [comment]
![image](https://github.com/KilJaeeun/TIL/assets/52051773/6be481b0-5ea0-4d8a-a7e9-7d0c92e1cfd5)

**Comment by KilJaeeun** [comment]
![image](https://github.com/KilJaeeun/TIL/assets/52051773/a2b2b292-e365-435a-b116-05cc515f0e8a)

**Comment by KilJaeeun** [comment]
![image](https://github.com/KilJaeeun/TIL/assets/52051773/afa2b38e-7c47-42cd-bc0d-bd2bd7aed397)
![image](https://github.com/KilJaeeun/TIL/assets/52051773/bfc6ddd8-8a11-49fd-abed-62b5e4dfcfe5)
![image](https://github.com/KilJaeeun/TIL/assets/52051773/81944b96-e8da-4a2e-ae2f-30625b3cfb55)
![image](https://github.com/KilJaeeun/TIL/assets/52051773/f00a4bba-e4a5-49a7-8a94-4e159e421403)
![image](https://github.com/KilJaeeun/TIL/assets/52051773/2031597f-ebeb-4bc7-b1d8-d17cdfcdf23d)
![image](https://github.com/KilJaeeun/TIL/assets/52051773/07ec3333-95e9-472e-8dfe-a4b1e989b49f)
helper 파일 -> helm create  first 섹션 : 레이블을 모든 앱에 달고 싶을때, 여기 달고 나중에  인용이 가능함. `{{ include "myapp.fullname." . }} `
![image](https://github.com/KilJaeeun/TIL/assets/52051773/4781eacc-7454-4aec-88ea-fecd6a062586)

**Comment by KilJaeeun** [comment]
![image](https://github.com/KilJaeeun/TIL/assets/52051773/4f23c9f9-04de-4df3-bc00-0ccc2db5c7d6)

**Comment by KilJaeeun** [comment]
https://static.sched.com/hosted_files/kccncna19/7c/Helm%20Intro.pdf

**Comment by KilJaeeun** [comment]
# helm hub
헬름 차트에 대한 헬름 허브 또는 모노큘러 인스턴스를 검색한다.

헬름허브는 공개적으로 사용 가능한 분산 형 차트에 대한 중앙 집중식 검색을 제공한다. 헬름 프로젝트에서 관리한다. https://hub.helm.sh/에서 방문 할 수 있다.

**Comment by KilJaeeun** [comment]
https://m.blog.naver.com/alice_k106/221570468691
### 2. Helm 차트를 배포하기 위한 저장소



도커 이미지를 배포하기 위해서는 ECR, 도커 허브 등이 필요하듯이, Helm 차트를 배포하기 위해서는 차트 저장소가 필요하다. 대표적인 예시로는 Helm을 설치하면 기본적으로 사용할 수 있는 stable 저장소가 있는데, 이는 Helm에서 공식적으로 제공되고 있기 때문에 별도의 설정을 하지 않아도 사용할 수 있다. 사용 가능한 저장소 목록은 helm repo list 명령어로 확인할 수 있다.







참고로, Helm 저장소 목록은 Tiller가 아닌 클라이언트 단 (~/.helm/repository/repositories.yaml) 에 저장된다.

**Comment by KilJaeeun** [comment]
# helm 2to3
https://github.com/helm/helm-2to3
![image](https://github.com/KilJaeeun/TIL/assets/52051773/32319dfc-82d2-498b-b9ca-0b5bfdad0253)

This is a Helm v3 plugin which migrates and cleans up Helm v2 configuration and releases in-place to Helm v3

**Comment by KilJaeeun** [comment]
https://github.com/helm/chart-releaser
About
Hosting Helm Charts via GitHub Pages and Releases

**Comment by KilJaeeun** [comment]
### defining scope using with

**Comment by KilJaeeun** [comment]
# 19. range
```md
 Looping with Range
  ~~~~~~~~~~~~~~~~~
  
  LangUsed:
    - Python
    - Ruby
    - Java
    - Scala
    
  LangUsed: |-
     {{- range .Values.LangUsed }}
     - {{ . | title | quote }}
     {{- end }}   
     
 title - Title case functions
 
 
 helm install --dry-run --debug controlif ./mychart
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
   NetSpeed: |-
     {{- range tuple "low" "medium" "high" }}
     - {{ . }}
     {{- end }}
  
  
 helm install --dry-run --debug controlif ./mychart
 
 
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by KilJaeeun** [comment]
## 20. variable 
```yaml
 {{- $relname := .Release.Name -}}
 {{- with .Values.tags }}
 Machine Type: {{ .machine | default "NA" | quote }}
 Rack ID: {{ .rack | quote }}
 Storage Type: {{ .drive | upper | quote }}
 Video Card: {{ .vcard | quote }}
 Release: {{ $relname }}
 {{- end }}
 
 
 helm install --dry-run --debug vartest ./mychart
 
 ~~~~~~~~~~~~~~
 
 LangUsed: |-
   {{- range $index, $topping := .Values.LangUsed }}
   - {{ $index }} : {{ $topping }}
   {{- end }} 
 
 
 ~~~~~~~~~~~~~~~~~~~~~~~~~
 
 tags:
   machine: frontdrive
   rack: 4c
   drive: ssd
   vcard: 8g
   
 
 tags: 
   {{- range $key, $value := .Values.tags }}
   {{ $key }} : {{ $value }}
   {{- end }} 
 
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 labels:
   helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
   app.kubernetes.io/instance: "{{ $.Release.Name }}"
   app.kubernetes.io/version: "{{ $.Chart.AppVersion }}"
  app.kubernetes.io/managed-by: "{{ $.Release.Service }}"
```
