### ISSUE TITLE
argoCD

### ISSUE THREAD

**Issue by KilJaeeun** [KilJaeeun/TIL#14]

**Comment by KilJaeeun** [comment]
# what is GItOps?

**Comment by KilJaeeun** [comment]
# argoCD
- argoCD  is a GitOPs based  CD with pull model design
- argoCD is a gitops based continous delivery tool 
  - so there will be a controller that pull the changes from repositories
![image](https://github.com/KilJaeeun/TIL/assets/52051773/4259290d-9004-4b5b-9eb2-7612aca1fb7a)

**Comment by KilJaeeun** [comment]
# what is ArgoCD?
- argoCD is a GitOps continous delivery tool for kubernets
![image](https://github.com/KilJaeeun/TIL/assets/52051773/86b027ae-2cf8-4dfd-9116-fb39b77e9023)
![image](https://github.com/KilJaeeun/TIL/assets/52051773/77cbd1fd-b296-4c28-a3f7-da288077e073)
![image](https://github.com/KilJaeeun/TIL/assets/52051773/a021a7be-b48d-485e-9fd8-0acdbc888ac4)
![image](https://github.com/KilJaeeun/TIL/assets/52051773/5bf947a6-aa15-4b93-8e65-5ef9f85a5aeb)
 
![image](https://github.com/KilJaeeun/TIL/assets/52051773/9f1872e0-7af4-45f6-be12-17e508ef5277)
![image](https://github.com/KilJaeeun/TIL/assets/52051773/00282a2c-b608-487d-8531-cd5177f7a1d1)

**Comment by KilJaeeun** [comment]
You need to create a namespace for argocd.

kubectl create ns argocd

and then choose one of the below options :

1. Non-HA:

a. cluster-admin privileges: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

b. namespace level privileges: https://github.com/argoproj/argo-cd/raw/stable/manifests/namespace-install.yaml



2. HA:

a. cluster-admin privileges: https://github.com/argoproj/argo-cd/raw/stable/manifests/ha/install.yaml

b. namespace level privileges: https://github.com/argoproj/argo-cd/raw/stable/manifests/ha/namespace-install.yaml

3. Light installation "Core"

https://github.com/argoproj/argo-cd/raw/stable/manifests/core-install.yaml

4. Helm chart: https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd

**Comment by KilJaeeun** [comment]
- 도커 데스크탑에 쿠베 기능
![image](https://github.com/KilJaeeun/TIL/assets/52051773/86f70cf8-3c88-497a-a459-2477fbf796ca)

**Comment by KilJaeeun** [comment]
# 11장. demo - getting initial admin password
- Get the initial admin password that is stored as a secret in Argo
CD namespace.
- Convert the secret from base64 into plain text

**Comment by KilJaeeun** [comment]
# 12장.
- argocd link : https://killercoda.com/mabusaa/course/argocd-endusers-scenarios/01-setting-up-argocd
If you face any issue or have a new suggestion , please raise it here: [issues tracker](https://github.com/mabusaa/argocd-course-issues-tracker/issues)

**Comment by KilJaeeun** [comment]
# 13장. accessing argoCD SERVER

**Comment by KilJaeeun** [comment]
# 16강. ArgoCD CLI
- You can interact with ArgoCD via
    -  CLI
    -  Web UI
    -  Rest/gRPC API
-  CLI is useful when you need to interact with ArgoCD in CI pipelines.

**Comment by KilJaeeun** [comment]
• ArgoCD CLI can be installed into all platforms
• Linux :
1. brew install argocd
or
2. yay -Sy argocd-bin
Or using curl
3. curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linuxamd64
• Mac :
1. brew install argocd
or using curl
2. VERSION=$(curl --silent "https://api.github.com/repos/argoproj/argo-cd/releases/latest" | grep '"tag_name"' |
sed -E 's/.*"([^"]+)".*/\1/’)
curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/$VERSION/argocddarwin-amd64
• Windows :
$version = (Invoke-RestMethod https://api.github.com/repos/argoproj/argo-cd/releases/latest).tag_name
$url = "https://github.com/argoproj/argo-cd/releases/download/" + $version + "/argocd-windows-amd64.exe"
$output = "argocd.exe" Invoke-WebRequest Slides by Muhammad Abusaa , Course Url → -Uri $url -OutFile $output

**Comment by KilJaeeun** [comment]
You need to login to ArgoCD Server before using any
command.
`argocd login <ARGOCD_SERVER>`
After successful login you can try using commands
`ex: argocd cluster list`

**Comment by KilJaeeun** [comment]
# 19강. 실습

Practice Link : [Installing Argo CD CLI](https://killercoda.com/mabusaa/course/argocd-endusers-scenarios/02-argocd-cli)

If you face any issue or have a new suggestion , please raise it here: [issues tracker](https://github.com/mabusaa/argocd-course-issues-tracker/issues)

**Comment by KilJaeeun** [comment]
# 섹션 4. applications
# 20강. defining applications
```
Application is a Kubernetes resource object representing a deployed application instance in an environment.
• It is defined by two key pieces of information:
• Source: reference to the desired state in Git (repository,
revision, path)
• Destination: reference to the target cluster and namespace.

```


## Applications can be created using below options
```
• Declaratively “Yaml”. (Recommended) • Web UI
• CLI
```
### Declaratively “Yaml”
```yaml
apiVersion: argoproj.io/v1alpha1 kind: Application
metadata:
    name: guestbook
    namespace: argocd 
spec:
    destination:
        namespace: guestbook
        server: "https://kubernetes.default.svc"
    project: default 
    source:
        path: guestbook
        repoURL: "https://github.com/argoproj/argocd-example-apps.git" 
        targetRevision: HEAD
```
![image](https://github.com/KilJaeeun/TIL/assets/52051773/7d8b66aa-5e50-4d09-a570-60d0a92eaa81)

## by Web UI
![image](https://github.com/KilJaeeun/TIL/assets/52051773/45322463-0d18-4f7e-bc78-0baed375fbb8)

## by CLI
```sh
argocd app create app-1 --repo https://github.com/mabusaa/argocd-example-apps.git --
path guestbook --dest-server https://kubernetes.default.svc --dest-namespace default
```

**Comment by KilJaeeun** [comment]
# 21강 자료
- https://github.com/mabusaa/argocd-course-apps-definitions/blob/main/applications%20and%20projects/application.yaml
- https://github.com/mabusaa/argocd-example-apps/tree/master/guestbook

**Comment by KilJaeeun** [comment]
# tools detection
## Tools supported
ArgoCD supports the below tools as source
- Helm charts
- Kustomize application 
- Directory of Yaml files. 
- Jsonnet

----


### yaml example

![image](https://github.com/KilJaeeun/TIL/assets/52051773/59967276-83c0-4c5c-87dd-3ca67e9150fd)


### helm example
![image](https://github.com/KilJaeeun/TIL/assets/52051773/e14709f1-e0e8-43fe-8296-38bd3eb562be)


### kustomize
![image](https://github.com/KilJaeeun/TIL/assets/52051773/a2124c44-3c33-4aef-bfa0-468d195a9823)



### not set , auto detected 
![image](https://github.com/KilJaeeun/TIL/assets/52051773/47bfffbd-5a19-4eb9-b2c5-6c94078e70bd)




### how argo

**Comment by KilJaeeun** [comment]
# Directory of files Options
ArgoCD provides the below as options
- Recursive: include all files in sub-directories.
- Jsonnet
   - External Vars : list of external variables for Jsonnet.
   - Top level Arguments.

##  Recursive
![image](https://github.com/KilJaeeun/TIL/assets/52051773/162ff563-aab1-40ff-9f53-f862fcbc9be5)



##  Jsonnet
![image](https://github.com/KilJaeeun/TIL/assets/52051773/c0b74dc5-ed2c-4142-ac09-e9f48d4ecf3c)


## Directory – Jsonnet Top Level Arguments
![image](https://github.com/KilJaeeun/TIL/assets/52051773/8cb6461a-c11d-47ef-9501-58939042d3ec)


# Kustomize Options
```
• Name prefix: appended to resources.
• Name suffix: appended to resources.
• Images : to override images.
• Common labels: set labels on all resources.
• Common annotations: set annotations on all resources. • Version: explicitly set kustomize version.
```
## Name Prefix
![image](https://github.com/KilJaeeun/TIL/assets/52051773/87e1f389-155b-487b-983a-f920ce6e4534)
## Name Suffix
![image](https://github.com/KilJaeeun/TIL/assets/52051773/b6c11a81-490f-4bc9-a6ba-8511e122e73e)

## Override Images
![image](https://github.com/KilJaeeun/TIL/assets/52051773/52abbfa3-e905-4e30-b55c-ace2408e576e)

## Common Labels
![image](https://github.com/KilJaeeun/TIL/assets/52051773/ff4fb5f0-9f48-4784-af90-04cc84121171)



## Common Annotations
![image](https://github.com/KilJaeeun/TIL/assets/52051773/1ea34a6c-64eb-47bc-bf79-9984c56f891b)


## version
![image](https://github.com/KilJaeeun/TIL/assets/52051773/d5c6b286-2a3f-4f61-a079-0cd5eb54ad98)

**Comment by KilJaeeun** [comment]
# Projects
- Application Grouping
- Projects provide a logical grouping of applications.
![image](https://github.com/KilJaeeun/TIL/assets/52051773/1aac5b12-1d10-4357-8adb-b4b3c1f89a69)

**Comment by KilJaeeun** [comment]
# HELM Options
- argocd provides the below for options
  - release name
  - values file
  - parameters
  - file parameters
  - values as block file
  - helm ㅇ

**Comment by KilJaeeun** [comment]
# directory of files options
## directory options
- argocd provide the below as options
 -  recursive : include all files in sub directories
 - jsonnet
     -  external vars : list of external variables for jsonnet
     - top level arguments

**Comment by KilJaeeun** [comment]
# directory - reculsive
```yaml
apiVersion: argoproj.io/v1alpha1 kind: Application
metadata:
      name: guestbook
      namespace: argocd 
spec:
      destination:
      namespace: guestbook
      server: "https://kubernetes.default.svc"
project: default 
source:
      path: guestbook
      repoURL: "https://github.com/argoproj/argocd-example-apps.git" 
      targetRevision: HEAD
      directory : 
         recursive : true  ## include all sub-driectories

```

# directory - jsonnet external variables
```yaml
apiVersion: argoproj.io/v1alpha1 kind: Application
metadata:
      name: guestbook
      namespace: argocd 
spec:
      destination:
      namespace: guestbook
      server: "https://kubernetes.default.svc"
project: default 
source:
      path: guestbook
      repoURL: "https://github.com/argoproj/argocd-example-apps.git" 
      targetRevision: HEAD
      directory : 
         jsonnet:
          extVars:
          - name: service
             values : "internal"

```

# directory - jsonnet top level arguments

```yaml

apiVersion: argoproj.io/v1alpha1 kind: Application
metadata:
      name: guestbook
      namespace: argocd 
spec:
      destination:
      namespace: guestbook
      server: "https://kubernetes.default.svc"
project: default 
source:
      path: guestbook
      repoURL: "https://github.com/argoproj/argocd-example-apps.git" 
      targetRevision: HEAD
      directory : 
         jsonnet:
           tlas:
           - name: service
              value: "internal"
              code: "false"

```





```

**Comment by KilJaeeun** [comment]
# kustomize options
## options
- argoCD  provides the below for options
   -  name prefix : appended to resources
   - name suffix : appended to resources
   - images : to override images
   - common labels : set labels on all resources
   - common annotations : set annotations on all resources
   - version : explicitly set kustomize version


## example

```yaml

apiVersion: argoproj.io/v1alpha1 kind: Application
metadata:
      name: guestbook
      namespace: argocd 
spec:
      destination:
      namespace: guestbook
      server: "https://kubernetes.default.svc"
project: default 
source:
      path: guestbook
      repoURL: "https://github.com/argoproj/argocd-example-apps.git" 
      targetRevision: HEAD
      kustomize: 
        nameSuffix : -staging # # adds a suffix to all resources names
        namePrefix : staging- # # adds a prefix to all resources names
        images:
        - gcr.io/heptio-images/ks-guestbook-demo:0.2 # Override images
        commonLabels: # labels
         app: demo
         appVersion: 1.0 
       commonAnnotations:  # annotations
         app: demo
         appVersion: 1.0 
      version: v3.5.4 # version 
```

**Comment by KilJaeeun** [comment]
# multiple source for an application 
- argo 2.6 버전 까지는 app 당 단일 소스였는데, 2.6부터 여러 소스 가능
```yaml
apiVersion: argoproj.io/v1alpha1 
kind: Application
metadata:
      name: multi-source
      namespace: argocd 
spec:
      destination:
      namespace: guestbook
      server: "https://kubernetes.default.svc"
project: default 
source:
   - chart: redis
      repoURL : "https://charts"
      targetRevision: 19.0.3
   - chart : promethous-redis-exporter
      repoURL: "https://github.com/argoproj/argocd-example-apps.git" 
      targetRevision: HEAD
```

**Comment by KilJaeeun** [comment]
# why projects
- application grouping 
  -  projects provide a logical grouping of applications
![image](https://github.com/KilJaeeun/TIL/assets/52051773/2786db2a-d019-49e7-814f-04f600adb7cb)


## access registration
- useful when argocd is used by multiple teams 
  -  allow only specific sources "trusted git repos"
  - allow apps to be deployed into specific cluster and namespaces
  - allow specific resources tobe deployed "deployments, statefulsets.. etc"

![image](https://github.com/KilJaeeun/TIL/assets/52051773/7c3fa33c-a3c8-47d4-a0f7-5f8ccd0c1d25)

**Comment by KilJaeeun** [comment]
# project roles feature
- enables you to create a role with set of policies "permissions" to grant access to a project's application
- you can use it to grant CI system a specific access to project application
  -   it must be associated with JWT
- you can use it  grant oidc groups a specific access to project applications 
![image](https://github.com/KilJaeeun/TIL/assets/52051773/f343bb78-2607-43b8-806b-4ead96dc43ad)

**Comment by KilJaeeun** [comment]
## Creating Projects Options
- Declaratively. 
-  CLI.
- Web UI.

### project yaml
```yaml
apiVersion: argoproj.io/v1alpha1 
kind: AppProject
metadata:
  name : project-1
  namespace: argocd
spec:
  description : project description
  source Repos:
  - "*"
  destinations:
  - server : "*"
     namespace : "*"
  clusterResourceWhiteList:
  - group : "*"
     kind : "*"
   namespaceResourceWhiteList:
   - group : "*"
      kind : "*"
```

### specific destination 
```yaml
apiVersion: argoproj.io/v1alpha1 
kind: AppProject
metadata:
  name : project-1
  namespace: argocd
spec:
  description : project description
  source Repos:
  - "*"
  destinations:
  - server : "*"
     namespace : "*"
  clusterResourceWhiteList:
  - group : "*"
     kind : "*"
   namespaceResourceWhiteList:
   - group : "*"
      kind : "*"
```

**Comment by KilJaeeun** [comment]
### Allow specific Cluster-scoped resources
```yaml
apiVersion: argoproj.io/v1alpha1 
kind: AppProject
metadata:
  name : project-1
  namespace: argocd
spec:
  description : project description
  source Repos: # only permit git repo
  - “https://github.com/mabusaa/argocd-example-apps.git”
  destinations:
  - server : "*"
     namespace : "*"
  clusterResourceWhiteList: # Deny all cluster-scoped resources from being created, except for Namespace
  - group : ""
     kind : "Namespace"
   namespaceResourceWhiteList:
   - group : "*"
      kind : "*"

```

### Allow specific Namespace- scoped resources
![image](https://github.com/KilJaeeun/TIL/assets/52051773/682bdfc7-ea0a-4c4b-9023-f51b0ca0cd79)

### Blacklist specific Namespace- scoped resources
![image](https://github.com/KilJaeeun/TIL/assets/52051773/74d5dac4-a030-4e6b-97d0-e95b96ee6707)

## Set project in application

![image](https://github.com/KilJaeeun/TIL/assets/52051773/5930c91d-04ac-4f80-a66b-c3e246c0f66d)
